<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="7" hostname="WILASSETA0041.local" failures="1" tests="1" name="TestCases" time="389.616" errors="0" timestamp="19 Jun 2023 14:27:50 GMT">
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyMoveAllIssueFromBacklogToSprint" time="327.752">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.PlanIT.WitsLab.tests.BacklogTestScript.verifyMoveAllIssueFromBacklogToSprint(BacklogTestScript.java:381)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMoveAllIssueFromBacklogToSprint -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="moveTicketFromOneBoardToAnother" time="0.0">
    <ignored/>
  </testcase> <!-- moveTicketFromOneBoardToAnother -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateIssueFromBoard" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCreateIssueFromBoard -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateSprintFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCreateSprintFunctionality -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifySprintActivation" time="0.0">
    <ignored/>
  </testcase> <!-- verifySprintActivation -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyAddMemberFunctionalityFromBoard" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAddMemberFunctionalityFromBoard -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCloneIssueFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCloneIssueFunctionality -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateIssueFromBacklogFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCreateIssueFromBacklogFunctionality -->
</testsuite> <!-- TestCases -->
